#pragma once
#ifdef RAMP_DISCRETE_FLOOR
    #undef RAMP_DISCRETE_FLOOR
#endif
#define RAMP_DISCRETE_FLOOR DEFAULT_LEVEL

#ifdef RAMP_DISCRETE_CEIL
    #undef RAMP_DISCRETE_CEIL
#endif
#define RAMP_DISCRETE_CEIL MAX_LEVEL

#ifdef RAMP_SMOOTH_CEIL
    #undef RAMP_SMOOTH_CEIL
#endif
#define RAMP_SMOOTH_CEIL MAX_LEVEL

#ifdef RAMP_STYLE
    #undef RAMP_STYLE
#endif
#define RAMP_STYLE 0

#ifdef RGB_LED_LOCKOUT_DEFAULT
    #undef RGB_LED_LOCKOUT_DEFAULT
#endif
#define RGB_LED_LOCKOUT_DEFAULT 0x29

#ifdef RGB_LED_OFF_DEFAULT
    #undef RGB_LED_OFF_DEFAULT
#endif
#define RGB_LED_OFF_DEFAULT 0x29

#ifdef SIMPLE_UI_ACTIVE
    #undef SIMPLE_UI_ACTIVE
#endif
#define SIMPLE_UI_ACTIVE 0

#ifdef DEFAULT_MANUAL_MEMORY
    #undef DEFAULT_MANUAL_MEMORY
#endif
#define DEFAULT_MANUAL_MEMORY DEFAULT_LEVEL

#ifdef DEFAULT_MANUAL_MEMORY_TIMER
    #undef DEFAULT_MANUAL_MEMORY_TIMER
#endif
#define DEFAULT_MANUAL_MEMORY_TIMER 4

#ifdef USE_AUTOLOCK
    #undef USE_AUTOLOCK
#endif
#define USE_AUTOLOCK

#ifdef DEFAULT_AUTOLOCK_TIME
    #undef DEFAULT_AUTOLOCK_TIME
#endif
#define DEFAULT_AUTOLOCK_TIME 0

#ifdef DEFAULT_POST_OFF_VOLTAGE_SECONDS
    #undef DEFAULT_POST_OFF_VOLTAGE_SECONDS
#endif
#define DEFAULT_POST_OFF_VOLTAGE_SECONDS 0

#ifdef DEFAULT_SMOOTH_STEPS_STYLE
    #undef DEFAULT_SMOOTH_STEPS_STYLE
#endif
#define DEFAULT_SMOOTH_STEPS_STYLE 0

#undef BLINK_AT_RAMP_CEIL
#undef BLINK_AT_RAMP_MIDDLE
#undef BLINK_AT_RAMP_FLOOR
