// Emisar D4K 3-channel hwdef
// Copyright (C) 2023-2026 Selene ToyKeeper
// SPDX-License-Identifier: GPL-3.0-or-later
#pragma once

// Scale factors for main2 channel (two green LEDs)
// 32 = 12.5%, 64 = 25%, 128 = 50%, 192 = 75%, 255 = 100%
#ifndef MAIN2_SCALE
#define MAIN2_SCALE 105      // 41% for CM_ALL - colorimetric D65 white
#endif
#ifndef MAIN2_SCALE_RGG
#define MAIN2_SCALE_RGG 32   // 12.5% for R+G,G (yellow/orange) - less green
#endif
#ifndef MAIN2_SCALE_GGB
#define MAIN2_SCALE_GGB 128  // 50% for G,G+B (cyan) - more green
#endif

// =============================================================================
// CCT Ramp Lookup Table - RGB values along Planckian locus
// Generated by tools/led_colorimetry.py using CIE 1931 colorimetry
//
// Default range: 2700K (warm incandescent) to 6500K (D65 daylight)
// Extended range available: 1800K to 10000K (define CCT_TABLE_EXTENDED)
//
// To regenerate tables:
//   Default:  python3 tools/led_colorimetry.py --config d4k-rgbg --cct-lut 2700 6500 16
//   Extended: python3 tools/led_colorimetry.py --config d4k-rgbg --cct-lut 1800 10000 16
//
// Index 0 = warm (lowest CCT), Index 15 = cool (highest CCT)
// Values are {R, G_scaled, B} where G is pre-scaled for RGBG config
// =============================================================================

#ifdef CCT_TABLE_EXTENDED
// Extended range: 1800K (candlelight) to 10000K (blue sky)
#define CCT_LUT_SIZE 16
#define CCT_MIN_K 1800
#define CCT_MAX_K 10000
PROGMEM const uint8_t cct_lut[CCT_LUT_SIZE][3] = {
    {255,  23,   4},  // [ 0] 1800K - candlelight
    {255,  32,  15},  // [ 1] 2346K
    {255,  39,  32},  // [ 2] 2893K
    {255,  45,  50},  // [ 3] 3440K
    {255,  50,  70},  // [ 4] 3986K
    {255,  53,  90},  // [ 5] 4533K
    {255,  56, 109},  // [ 6] 5080K
    {255,  59, 127},  // [ 7] 5626K
    {255,  61, 144},  // [ 8] 6173K
    {255,  63, 159},  // [ 9] 6720K
    {255,  64, 174},  // [10] 7266K
    {255,  65, 187},  // [11] 7813K
    {255,  66, 198},  // [12] 8360K
    {255,  67, 209},  // [13] 8906K
    {255,  68, 219},  // [14] 9453K
    {255,  68, 228},  // [15] 10000K - blue sky
};
#else
// Default range: 2700K (warm incandescent) to 6500K (D65 daylight)
#define CCT_LUT_SIZE 16
#define CCT_MIN_K 2700
#define CCT_MAX_K 6500
PROGMEM const uint8_t cct_lut[CCT_LUT_SIZE][3] = {
    {255,  37,  25},  // [ 0] 2700K - warm incandescent
    {255,  40,  33},  // [ 1] 2953K
    {255,  43,  42},  // [ 2] 3206K
    {255,  45,  51},  // [ 3] 3460K
    {255,  47,  60},  // [ 4] 3713K
    {255,  49,  69},  // [ 5] 3966K
    {255,  51,  79},  // [ 6] 4220K
    {255,  53,  88},  // [ 7] 4473K
    {255,  55,  97},  // [ 8] 4726K
    {255,  56, 106},  // [ 9] 4980K
    {255,  57, 114},  // [10] 5233K
    {255,  58, 123},  // [11] 5486K
    {255,  59, 131},  // [12] 5740K
    {255,  60, 139},  // [13] 5993K
    {255,  61, 146},  // [14] 6246K
    {255,  62, 153},  // [15] 6500K - D65 daylight
};
#endif

#include "anduril/channel-modes.h"  //for circular_tint_3h()
#include "fsm/chan-rgbaux.c"


void set_level_zero();

void set_level_main2(uint8_t level);
void set_level_led3(uint8_t level);
void set_level_led4(uint8_t level);
void set_level_all(uint8_t level);
void set_level_led34a_blend(uint8_t level);
void set_level_led34b_blend(uint8_t level);
void set_level_hsv(uint8_t level);
void set_level_auto3(uint8_t level);
void set_level_cct(uint8_t level);

bool gradual_tick_main2(uint8_t gt);
bool gradual_tick_led3(uint8_t gt);
bool gradual_tick_led4(uint8_t gt);
bool gradual_tick_all(uint8_t gt);
bool gradual_tick_led34a_blend(uint8_t gt);
bool gradual_tick_led34b_blend(uint8_t gt);
bool gradual_tick_hsv(uint8_t gt);
bool gradual_tick_auto3(uint8_t gt);
bool gradual_tick_cct(uint8_t gt);


Channel channels[] = {
    { // main 2 LEDs only
        .set_level    = set_level_main2,
        .gradual_tick = gradual_tick_main2,
        .flags        = 0
    },
    { // 3rd LED only
        .set_level    = set_level_led3,
        .gradual_tick = gradual_tick_led3,
        .flags        = 0
    },
    { // 4th LED only
        .set_level    = set_level_led4,
        .gradual_tick = gradual_tick_led4,
        .flags        = 0
    },
    { // all channels, tied together (equal amounts, max power)
        .set_level    = set_level_all,
        .gradual_tick = gradual_tick_all,
        .flags        = 0
    },
    { // 3rd + 4th LEDs, manual blend (max "100%" power) (8/16/16)
        .set_level    = set_level_led34a_blend,
        .gradual_tick = gradual_tick_led34a_blend,
        .flags        = CHANNEL_FLAG_HAS_ARGS
    },
    { // 3rd + 4th LEDs, manual blend (max "100%" power) (16/16/8)
        .set_level    = set_level_led34b_blend,
        .gradual_tick = gradual_tick_led34b_blend,
        .flags        = CHANNEL_FLAG_HAS_ARGS
    },
    { // 3ch blend (HSV style)
        .set_level    = set_level_hsv,
        .gradual_tick = gradual_tick_hsv,
        .flags        = CHANNEL_FLAG_HAS_ARGS
    },
    { // 3ch auto blend (red-warm-cool style, led4-led3-main2)
        .set_level    = set_level_auto3,
        .gradual_tick = gradual_tick_auto3,
        .flags        = 0
    },
    { // CCT ramp mode: 2700K (warm) to 6500K (cool) along Planckian locus
        .set_level    = set_level_cct,
        .gradual_tick = gradual_tick_cct,
        .flags        = CHANNEL_FLAG_HAS_ARGS
    },
    AUXRGB_CHANNELS
};

// HSV mode needs a different 3H handler (circular wrap-around)
// CCT mode uses default linear 3H (warm to cool)
StatePtr channel_3H_modes[NUM_CHANNEL_MODES] = {
    NULL, NULL, NULL, NULL,
    NULL, NULL, circular_tint_3h, NULL, NULL,
};

void set_level_zero() {
    // disable timer overflow interrupt
    // (helps improve button press handling from Off state)
    DSM_INTCTRL &= ~DSM_OVF_bm;

    // turn off all LEDs
    MAIN2_ENABLE_PORT &= ~(1 << MAIN2_ENABLE_PIN);
    LED3_ENABLE_PORT  &= ~(1 << LED3_ENABLE_PIN );
    LED4_ENABLE_PORT  &= ~(1 << LED4_ENABLE_PIN );
    main2_dsm_lvl = 0;
    led3_dsm_lvl  = 0;
    led4_dsm_lvl  = 0;
    MAIN2_PWM_LVL = 0;
    LED3_PWM_LVL  = 0;
    LED4_PWM_LVL  = 0;
    PWM_CNT       = 0;
    //PWM_TOP       = PWM_TOP_INIT;
}

// wrap setting the dsm vars, to get a faster response
// (just setting *_dsm_lvl doesn't work well for strobes)
void set_hw_levels(PWM_DATATYPE main2, // brightness, 0 to DSM_TOP
                   PWM_DATATYPE led3,
                   PWM_DATATYPE led4,
                   bool main2_en,      // enable even at PWM=0?
                   bool led3_en,
                   bool led4_en
                   ) {

    // enable/disable LED power channels
    if (main2 | main2_en)
         MAIN2_ENABLE_PORT |=  (1 << MAIN2_ENABLE_PIN);
    else MAIN2_ENABLE_PORT &= ~(1 << MAIN2_ENABLE_PIN);

    if (led3  | led3_en )
         LED3_ENABLE_PORT  |=  (1 << LED3_ENABLE_PIN);
    else LED3_ENABLE_PORT  &= ~(1 << LED3_ENABLE_PIN);

    if (led4  | led4_en )
         LED4_ENABLE_PORT  |=  (1 << LED4_ENABLE_PIN);
    else LED4_ENABLE_PORT  &= ~(1 << LED4_ENABLE_PIN);

    // set delta-sigma soft levels
    main2_dsm_lvl = main2;
    led3_dsm_lvl  = led3;
    led4_dsm_lvl  = led4;
    // set hardware PWM levels and init dsm loop
    MAIN2_PWM_LVL = main2_pwm = main2 >> 7;
    LED3_PWM_LVL  = led3_pwm  = led3  >> 7;
    LED4_PWM_LVL  = led4_pwm  = led4  >> 7;

    // enable timer overflow interrupt so DSM can work
    DSM_INTCTRL |= DSM_OVF_bm;

    // force phase reset
    PWM_CNT       = PWM_CNT2  = 0;
}

// delta-sigma modulation of PWM outputs
// happens on each Timer overflow (every 512 cpu clock cycles)
// uses 8-bit pwm w/ 7-bit dsm (0b 0PPP PPPP PDDD DDDD)
ISR(DSM_vect) {
    // set new hardware values first,
    // for best timing (reduce effect of interrupt jitter)
    MAIN2_PWM_LVL = main2_pwm;
    LED3_PWM_LVL  = led3_pwm;
    LED4_PWM_LVL  = led4_pwm;

    // calculate next values, now that timing matters less

    // accumulate error
    main2_dsm += (main2_dsm_lvl & 0x007f);
    // next PWM = base PWM value + carry bit
    main2_pwm  = (main2_dsm_lvl >> 7) + (main2_dsm > 0x7f);
    // clear carry bit
    main2_dsm &= 0x7f;

    // repeat for other channels

    led3_dsm += (led3_dsm_lvl & 0x007f);
    led3_pwm  = (led3_dsm_lvl >> 7) + (led3_dsm > 0x7f);
    led3_dsm &= 0x7f;

    led4_dsm += (led4_dsm_lvl & 0x007f);
    led4_pwm  = (led4_dsm_lvl >> 7) + (led4_dsm > 0x7f);
    led4_dsm &= 0x7f;
}

// LEDs 1+2 are 8-bit
// this 8-bit channel may be LEDs 1+2 or LED 4, depending on wiring
void set_level_main2(uint8_t level) {
    set_hw_levels(PWM_GET(pwm1_levels, level), 0, 0,
                  1,                           0, 0);
}

// LED 3 is 16-bit
void set_level_led3(uint8_t level) {
    set_hw_levels(0, PWM_GET(pwm1_levels, level), 0,
                  0, 1,                           0);
}

// this 16-bit channel may be LED 4 or LEDs 1+2, depending on wiring
void set_level_led4(uint8_t level) {
    set_hw_levels(0, 0, PWM_GET(pwm1_levels, level),
                  0, 0, 1);
}

void set_level_all(uint8_t level) {
    PWM_DATATYPE pwm = PWM_GET(pwm1_levels, level);
    // Scale down main2 (green LEDs) for balanced color mixing
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)pwm * MAIN2_SCALE) >> 8;
    set_hw_levels(main2_scaled, pwm, pwm, 1, 1, 1);
}

// 8/16/16 wiring, mix 16+16
void set_level_led34a_blend(uint8_t level) {
    PWM_DATATYPE warm_PWM, cool_PWM;
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, level);
    uint8_t blend = cfg.channel_mode_args[channel_mode];

    calc_2ch_blend(&warm_PWM, &cool_PWM, brightness, DSM_TOP, blend);

    set_hw_levels(0, warm_PWM,    cool_PWM,
                  0, (blend<170), (blend>85));
}

// R,G,G blend: main2 (G,G) + led3 (R), no led4 (B) - yellow/orange
void set_level_led34b_blend(uint8_t level) {
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, level);

    // Scale main2 (green LEDs) lower for better yellow/orange
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)brightness * MAIN2_SCALE_RGG) >> 8;

    // main2 (G,G scaled) + led3 (R) at full brightness
    set_hw_levels(main2_scaled, brightness, 0,
                  1,            1,          0);
}

void set_level_hsv(uint8_t level) {
    RGB_t color;
    uint8_t h = cfg.channel_mode_args[channel_mode];
    uint8_t s = 255;  // TODO: drop saturation at brightest levels
    PWM_DATATYPE v = PWM_GET(pwm1_levels, level);
    color = hsv2rgb(h, s, v);

    // Scale down main2 (green LEDs) for balanced color mixing
    // main2 has 2 LEDs so it's naturally brighter
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)color.r * MAIN2_SCALE) >> 8;

    set_hw_levels(main2_scaled, color.g, color.b,
                  0,            0,       0);
}

// calculate a 3-channel "auto tint" blend
// (like red -> warm white -> cool white)
// results are placed in *a, *b, and *c vars
// level : ramp level to convert into 3 channel levels
// (assumes ramp table is "pwm1_levels")
void calc_auto_3ch_blend(
    PWM_DATATYPE *a,  // red
    PWM_DATATYPE *b,  // warm
    PWM_DATATYPE *c,  // cool
    uint8_t level) {

    PWM_DATATYPE vpwm  = PWM_GET(pwm1_levels, level);

    // tint goes from 0 (red) to 127 (warm white) to 255 (cool white)
    uint8_t mytint;
    mytint = 255 * (uint16_t)(level+1) / RAMP_SIZE;

    uint8_t falling=0, rising=0;
    if (level < (RAMP_SIZE/2))
        falling = 255 - triangle_wave(mytint);
    else
        rising = 255 - triangle_wave(mytint);

    // TODO: make "a" drop to zero sooner, and "c" start ramping up later
    // red is high at 0, low at 255 (linear)
    *a = (((PWM_DATATYPE2)falling
         * (PWM_DATATYPE2)vpwm) + 127) / 255;
    // warm white is low at 0 and 255, high at 127 (linear triangle)
    *b = (((PWM_DATATYPE2)triangle_wave(mytint)
         * (PWM_DATATYPE2)vpwm)      ) / 255;
    // cool white is low at 0, high at 255 (linear)
    *c = (((PWM_DATATYPE2)rising
         * (PWM_DATATYPE2)vpwm) + 127) / 255;

}

// G,G+B (cyan) blend: main2 (G,G) + led4 (B), no led3 (R)
void set_level_auto3(uint8_t level) {
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, level);

    // Scale main2 (green LEDs) higher for better cyan
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)brightness * MAIN2_SCALE_GGB) >> 8;

    // main2 (G,G scaled) + led4 (B) at full brightness
    set_hw_levels(main2_scaled, 0, brightness,
                  1,            0, 1);
}

///// "gradual tick" functions for smooth thermal regulation /////
// (and other smooth adjustments)

bool gradual_adjust(PWM_DATATYPE main2, PWM_DATATYPE led3, PWM_DATATYPE led4) {
    // adjust multiple times based on current brightness
    // (so it adjusts faster/coarser when bright, slower/finer when dim)

    // higher shift = slower/finer adjustments
    const uint8_t shift = 9;  // ((255 << 7) >> 9) = 63 max
    uint8_t steps;

    steps = main2_dsm_lvl >> shift;
    for (uint8_t i=0; i<=steps; i++)
        GRADUAL_ADJUST_SIMPLE(main2, main2_dsm_lvl);

    steps = led3_dsm_lvl  >> shift;
    for (uint8_t i=0; i<=steps; i++)
        GRADUAL_ADJUST_SIMPLE(led3,  led3_dsm_lvl );

    steps = led4_dsm_lvl  >> shift;
    for (uint8_t i=0; i<=steps; i++)
        GRADUAL_ADJUST_SIMPLE(led4,  led4_dsm_lvl );

    if ((main2 == main2_dsm_lvl)
     && (led3  == led3_dsm_lvl )
     && (led4  == led4_dsm_lvl )) {
        return true;  // done
    }
    return false;  // not done yet
}

bool gradual_tick_main2(uint8_t gt) {
    PWM_DATATYPE main2 = PWM_GET(pwm1_levels, gt);
    return gradual_adjust(main2, 0, 0);
}

bool gradual_tick_led3(uint8_t gt) {
    PWM_DATATYPE led3 = PWM_GET(pwm1_levels, gt);
    return gradual_adjust(0, led3, 0);
}

bool gradual_tick_led4(uint8_t gt) {
    PWM_DATATYPE led4 = PWM_GET(pwm1_levels, gt);
    return gradual_adjust(0, 0, led4);
}

bool gradual_tick_all(uint8_t gt) {
    PWM_DATATYPE pwm = PWM_GET(pwm1_levels, gt);
    // Scale down main2 (green LEDs) to match set_level_all
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)pwm * MAIN2_SCALE) >> 8;
    return gradual_adjust(main2_scaled, pwm, pwm);
}

// 8/16/16 wiring, mix 16+16
bool gradual_tick_led34a_blend(uint8_t gt) {
    PWM_DATATYPE warm_PWM, cool_PWM;
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, gt);
    uint8_t blend = cfg.channel_mode_args[channel_mode];

    calc_2ch_blend(&warm_PWM, &cool_PWM, brightness, DSM_TOP, blend);

    return gradual_adjust(0, warm_PWM, cool_PWM);
}

// R,G,G blend: main2 (G,G) + led3 (R), no led4 (B) - yellow/orange
bool gradual_tick_led34b_blend(uint8_t gt) {
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, gt);

    // Scale main2 (green LEDs) to match set_level_led34b_blend
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)brightness * MAIN2_SCALE_RGG) >> 8;

    return gradual_adjust(main2_scaled, brightness, 0);
}

bool gradual_tick_hsv(uint8_t gt) {
    // figure out what exact PWM levels we're aiming for
    RGB_t color;
    uint8_t h = cfg.channel_mode_args[channel_mode];
    uint8_t s = 255;  // TODO: drop saturation at brightest levels
    PWM_DATATYPE v = PWM_GET(pwm1_levels, gt);
    color = hsv2rgb(h, s, v);

    // Scale down main2 (green LEDs) to match set_level_hsv
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)color.r * MAIN2_SCALE) >> 8;

    return gradual_adjust(main2_scaled, color.g, color.b);
}

// G,G+B (cyan) blend: main2 (G,G) + led4 (B), no led3 (R)
bool gradual_tick_auto3(uint8_t gt) {
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, gt);

    // Scale main2 (green LEDs) to match set_level_auto3
    PWM_DATATYPE main2_scaled = ((PWM_DATATYPE2)brightness * MAIN2_SCALE_GGB) >> 8;

    return gradual_adjust(main2_scaled, 0, brightness);
}

///// CCT (Color Temperature) Ramp Mode /////
// Produces white light along the Planckian locus from 2700K to 6500K
// 3H adjusts color temperature: 0 = warm (2700K), 255 = cool (6500K)
// Uses precomputed lookup table for accurate blackbody colors

// Helper: interpolate between two LUT entries
static void cct_get_rgb(uint8_t cct_arg, uint8_t *r, uint8_t *g, uint8_t *b) {
    // Map 0-255 arg to LUT index (0 to CCT_LUT_SIZE-1)
    // Use fixed-point math: index = arg * (CCT_LUT_SIZE-1) / 255
    uint16_t scaled = (uint16_t)cct_arg * (CCT_LUT_SIZE - 1);
    uint8_t idx = scaled >> 8;  // integer part (0 to CCT_LUT_SIZE-2)
    uint8_t frac = scaled & 0xFF;  // fractional part for interpolation

    // Clamp index to valid range
    if (idx >= CCT_LUT_SIZE - 1) {
        idx = CCT_LUT_SIZE - 2;
        frac = 255;
    }

    // Read adjacent LUT entries from PROGMEM
    uint8_t r0 = pgm_read_byte(&cct_lut[idx][0]);
    uint8_t g0 = pgm_read_byte(&cct_lut[idx][1]);
    uint8_t b0 = pgm_read_byte(&cct_lut[idx][2]);
    uint8_t r1 = pgm_read_byte(&cct_lut[idx + 1][0]);
    uint8_t g1 = pgm_read_byte(&cct_lut[idx + 1][1]);
    uint8_t b1 = pgm_read_byte(&cct_lut[idx + 1][2]);

    // Linear interpolation: result = v0 + (v1 - v0) * frac / 256
    *r = r0 + (((int16_t)(r1 - r0) * frac) >> 8);
    *g = g0 + (((int16_t)(g1 - g0) * frac) >> 8);
    *b = b0 + (((int16_t)(b1 - b0) * frac) >> 8);
}

void set_level_cct(uint8_t level) {
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, level);
    uint8_t cct_arg = cfg.channel_mode_args[channel_mode];

    // Get RGB ratios from CCT lookup table
    uint8_t r_ratio, g_ratio, b_ratio;
    cct_get_rgb(cct_arg, &r_ratio, &g_ratio, &b_ratio);

    // Scale by brightness
    // R goes to led3, G (already scaled in LUT) goes to main2, B goes to led4
    PWM_DATATYPE led3_pwm  = ((PWM_DATATYPE2)brightness * r_ratio) >> 8;
    PWM_DATATYPE main2_pwm = ((PWM_DATATYPE2)brightness * g_ratio) >> 8;
    PWM_DATATYPE led4_pwm  = ((PWM_DATATYPE2)brightness * b_ratio) >> 8;

    set_hw_levels(main2_pwm, led3_pwm, led4_pwm, 1, 1, 1);
}

bool gradual_tick_cct(uint8_t gt) {
    PWM_DATATYPE brightness = PWM_GET(pwm1_levels, gt);
    uint8_t cct_arg = cfg.channel_mode_args[channel_mode];

    // Get RGB ratios from CCT lookup table
    uint8_t r_ratio, g_ratio, b_ratio;
    cct_get_rgb(cct_arg, &r_ratio, &g_ratio, &b_ratio);

    // Scale by brightness (same as set_level_cct)
    PWM_DATATYPE led3_pwm  = ((PWM_DATATYPE2)brightness * r_ratio) >> 8;
    PWM_DATATYPE main2_pwm = ((PWM_DATATYPE2)brightness * g_ratio) >> 8;
    PWM_DATATYPE led4_pwm  = ((PWM_DATATYPE2)brightness * b_ratio) >> 8;

    return gradual_adjust(main2_pwm, led3_pwm, led4_pwm);
}

